### ISSUE TITLE
What version of cellprofiler should I be using?

### ISSUE THREAD

**Issue by ctr26** [CellProfiler/CellProfiler-plugins#103]
I've installed the latest cellprofiler on mac because the other versions generally fail. When I run cellprofiler with this plugin collection: 

If it needs cellprofiler3 (which I've read doesn't produce a GUI on linux) how do you add these modules to the pipeline?

All I really need is the unet module.

Best

Craig

```

(base) base ❯ cellprofiler --plugins-directory ~/CellProfiler-plugins
zsh: /usr/local/Caskroom/miniconda/base/bin/cellprofiler: bad interpreter: /usr/local/Caskroom/miniconda/base/bin/python3.8: no such file or directory
11:55:47: Debug: Adding duplicate image handler for 'Windows bitmap file'
11:55:47: Debug: Adding duplicate animation handler for '1' type
11:55:47: Debug: Adding duplicate animation handler for '2' type

Bad key "text.kerning_factor" on line 4 in
/usr/local/lib/python3.8/site-packages/matplotlib/mpl-data/stylelib/_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.1.3/matplotlibrc.template
or from the matplotlib source distribution
Could not load save_16bit_pngs
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/save_16bit_pngs.py", line 19, in <module>
    import cellprofiler.image
ImportError: bad magic number in 'cellprofiler.image': b'\x03\xf3\r\n'
Could not load runimagej
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/runimagej.py", line 3, in <module>
    import StringIO
ModuleNotFoundError: No module named 'StringIO'
Could not load laplacianofgaussian
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/laplacianofgaussian.py", line 7, in <module>
    import cellprofiler.image
ImportError: bad magic number in 'cellprofiler.image': b'\x03\xf3\r\n'
Could not load DoGNet
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/DoGNet.py", line 6, in <module>
    import dognet
ModuleNotFoundError: No module named 'dognet'
Could not load exporttocellh5
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/exporttocellh5.py", line 18, in <module>
    import cellprofiler.module as cpm
ModuleNotFoundError: No module named 'cellprofiler.module'
Could not load measureimagefocus
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/measureimagefocus.py", line 4, in <module>
    import cellprofiler.measurement
ImportError: bad magic number in 'cellprofiler.measurement': b'\x03\xf3\r\n'
Could not load rescale_mode_percentile
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/rescale_mode_percentile.py", line 19, in <module>
    import cellprofiler.image
ImportError: bad magic number in 'cellprofiler.image': b'\x03\xf3\r\n'
Could not load tophattransform
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/tophattransform.py", line 15, in <module>
    import cellprofiler.module
ModuleNotFoundError: No module named 'cellprofiler.module'
Could not load calculatemoments
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/calculatemoments.py", line 38, in <module>
    import cellprofiler.image as cpi
ImportError: bad magic number in 'cellprofiler.image': b'\x03\xf3\r\n'
Could not load identifylinearobjects
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/identifylinearobjects.py", line 14, in <module>
    import cellprofiler.module as cpm
ModuleNotFoundError: No module named 'cellprofiler.module'
Could not load identifyyeastcells
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/identifyyeastcells.py", line 132, in <module>
    import cellprofiler.measurement as cpmeas
ImportError: bad magic number in 'cellprofiler.measurement': b'\x03\xf3\r\n'
Could not load measuretrackquality
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/measuretrackquality.py", line 28, in <module>
    import cellprofiler.measurement as cpmeas
ImportError: bad magic number in 'cellprofiler.measurement': b'\x03\xf3\r\n'
Could not load transformfilters
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/transformfilters.py", line 279
    sub=np.zeros([ny, nx])
                         ^
TabError: inconsistent use of tabs and spaces in indentation
Could not load shollanalysis
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/shollanalysis.py", line 29, in <module>
    import cellprofiler.measurement
ImportError: bad magic number in 'cellprofiler.measurement': b'\x03\xf3\r\n'
Could not load randomwalkeralgorithm
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/randomwalkeralgorithm.py", line 16, in <module>
    import cellprofiler.module
ModuleNotFoundError: No module named 'cellprofiler.module'
Could not load callbarcodes
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/callbarcodes.py", line 13, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'
Could not load predict
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/predict.py", line 9, in <module>
    import cellprofiler.image
ImportError: bad magic number in 'cellprofiler.image': b'\x03\xf3\r\n'
Could not load classifypixelsunet
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/classifypixelsunet.py", line 58, in <module>
    import cellprofiler.module
ModuleNotFoundError: No module named 'cellprofiler.module'
Could not load measure_population_context
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/measure_population_context.py", line 35, in <module>
    import cellprofiler.module as cpm
ModuleNotFoundError: No module named 'cellprofiler.module'
Could not load blobdetection
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/blobdetection.py", line 20, in <module>
    import cellprofiler.image
ImportError: bad magic number in 'cellprofiler.image': b'\x03\xf3\r\n'
Could not load seedobjects
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/seedobjects.py", line 44, in <module>
    import cellprofiler.image
ImportError: bad magic number in 'cellprofiler.image': b'\x03\xf3\r\n'
Could not load histogramequalization
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/histogramequalization.py", line 10, in <module>
    import cellprofiler.image
ImportError: bad magic number in 'cellprofiler.image': b'\x03\xf3\r\n'
Could not load spectralanalysis
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/spectralanalysis.py", line 1210
    print result['orientation_mixed']
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(result['orientation_mixed'])?
Could not load calculatehistogram
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/calculatehistogram.py", line 18, in <module>
    import cellprofiler.image as cpi
ImportError: bad magic number in 'cellprofiler.image': b'\x03\xf3\r\n'
Could not load activecontourmodel
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/activecontourmodel.py", line 10, in <module>
    import cellprofiler.module
ModuleNotFoundError: No module named 'cellprofiler.module'
Could not load transform
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/transform.py", line 272
    print "Maximum number of scales exceeded."
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Maximum number of scales exceeded.")?
Could not load mergeobjects
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/mergeobjects.py", line 30, in <module>
    import cellprofiler.image
ImportError: bad magic number in 'cellprofiler.image': b'\x03\xf3\r\n'
Could not load nucleaizer
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/nucleaizer.py", line 52, in <module>
    import cellprofiler.image
ImportError: bad magic number in 'cellprofiler.image': b'\x03\xf3\r\n'
Could not load edgedetection
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/edgedetection.py", line 11, in <module>
    import cellprofiler.image
ImportError: bad magic number in 'cellprofiler.image': b'\x03\xf3\r\n'
Could not load constrainobjects
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/constrainobjects.py", line 24, in <module>
    import cellprofiler.image
ImportError: bad magic number in 'cellprofiler.image': b'\x03\xf3\r\n'
Could not load rescale_mean_sd
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/rescale_mean_sd.py", line 18, in <module>
    import cellprofiler.image
ImportError: bad magic number in 'cellprofiler.image': b'\x03\xf3\r\n'
Could not load gammacorrection
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/gammacorrection.py", line 8, in <module>
    import cellprofiler.module
ModuleNotFoundError: No module named 'cellprofiler.module'
Could not load declump
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/declump.py", line 40, in <module>
    import cellprofiler.image
ImportError: bad magic number in 'cellprofiler.image': b'\x03\xf3\r\n'
Could not load enhancedmeasuretexture
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/enhancedmeasuretexture.py", line 124, in <module>
    import calculatemoments as cpmoments
  File "/Users/ctr26/CellProfiler-plugins/calculatemoments.py", line 38, in <module>
    import cellprofiler.image as cpi
ImportError: bad magic number in 'cellprofiler.image': b'\x03\xf3\r\n'
Could not load compensatecolors
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/compensatecolors.py", line 17, in <module>
    import cellprofiler.image
ImportError: bad magic number in 'cellprofiler.image': b'\x03\xf3\r\n'
Could not load measureradialentropy
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/measureradialentropy.py", line 16, in <module>
    import cellprofiler.module as cpm
ModuleNotFoundError: No module named 'cellprofiler.module'
Could not load imagegradient
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/imagegradient.py", line 11, in <module>
    import cellprofiler.image
ImportError: bad magic number in 'cellprofiler.image': b'\x03\xf3\r\n'
Could not load convertoutlinestoobjects
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/__init__.py", line 135, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/Users/ctr26/CellProfiler-plugins/convertoutlinestoobjects.py", line 24, in <module>
    import cellprofiler.module
ModuleNotFoundError: No module named 'cellprofiler.module'
could not load these modules: save_16bit_pngs,runimagej,laplacianofgaussian,DoGNet,exporttocellh5,measureimagefocus,rescale_mode_percentile,tophattransform,calculatemoments,identifylinearobjects,identifyyeastcells,measuretrackquality,transformfilters,shollanalysis,randomwalkeralgorithm,callbarcodes,predict,classifypixelsunet,measure_population_context,blobdetection,seedobjects,histogramequalization,spectralanalysis,calculatehistogram,activecontourmodel,transform,mergeobjects,nucleaizer,edgedetection,constrainobjects,rescale_mean_sd,gammacorrection,declump,enhancedmeasuretexture,compensatecolors,measureradialentropy,imagegradient,convertoutlinestoobjects`
```

**Comment by bethac07** [comment]
The plugins have not been updated for CellProfiler 4; except for those in the "CellProfiler2" folder, as of today they expect some version of CellProfiler 3.  

As we work towards release in the next few weeks, most if not all of these plugins will be upgraded to CellProfiler 4 if possible.

**Comment by ctr26** [comment]
If it needs cellprofiler3 (which I've read doesn't produce a GUI on linux) how do you add these modules to the pipeline?

**Comment by bethac07** [comment]
CellProfiler3 can definitely make a Linux GUI.  

>CP3 is nigh impossible to install on mac, dependency hell

Yeah, as brew has retired some packages and pip has retired some others, it has become much more difficult.
