### ISSUE TITLE
Error while running RunImageJScript plugin

### ISSUE THREAD

**Issue by sugan89** [CellProfiler/CellProfiler-plugins#217]
I got the following error when I tried to run the `RunImageJScript` plugin, 

```
Starting CellProfiler 4.2.6
Process SpawnProcess-1:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "C:\Users\ssivagur\CellProfiler-plugins\active_plugins\cpij\server.py", line 496, in main
    _start_imagej_process()
  File "C:\Users\ssivagur\CellProfiler-plugins\active_plugins\cpij\server.py", line 334, in _start_imagej_process
    ij = imagej.init()
  File "C:\Program Files\CellProfiler\imagej\__init__.py", line 1200, in init
    success = _create_jvm(ij_dir_or_version_or_endpoint, mode, add_legacy)
  File "C:\Program Files\CellProfiler\imagej\__init__.py", line 1424, in _create_jvm
    sj.start_jvm()
  File "C:\Program Files\CellProfiler\scyjava\_java.py", line 190, in start_jvm
    _, workspace = jgo.resolve_dependencies(
  File "C:\Program Files\CellProfiler\jgo\jgo.py", line 640, in resolve_dependencies
    mvn = executable_path_or_raise("mvn")
  File "C:\Program Files\CellProfiler\jgo\jgo.py", line 199, in executable_path_or_raise
    raise ExecutableNotFound(tool, os.getenv("PATH"))
jgo.jgo.ExecutableNotFound: mvn not found on path C:\Users\ssivagur\Anaconda3\condabin;C:\Program Files\Eclipse Adoptium\jdk-11.0.20.8-hotspot\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\PuTTY\;C:\Program Files\GitHub CLI\;C:\Program Files (x86)\DVC (Data Version Control);C:\Users\ssivagur\Anaconda3\;C:\Program Files\Amazon\AWSCLIV2\;C:\Program Files\Docker\Docker\resources\bin;C:\Users\ssivagur\AppData\Local\Microsoft\WindowsApps;C:\Users\ssivagur\AppData\Local\atom\bin;C:\Users\ssivagur\AppData\Local\Pandoc\;C:\Users\ssivagur\AppData\Local\GitHubDesktop\bin;C:\Users\ssivagur\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\ssivagur\Anaconda3\;;C:\Program Files\CellProfiler\java\bin\client;C:\Program Files\CellProfiler\java\bin;C:\Program Files\CellProfiler\java\bin\client;C:\Program Files\CellProfiler\java\bin;C:\Program Files\CellProfiler\java\bin\client;C:\Program Files\CellProfiler\java\bin;C:\Program Files\CellProfiler\java\bin\client;C:\Program Files\CellProfiler\java\bin;C:\Program Files\CellProfiler\java\bin\client;C:\Program Files\CellProfiler\java\bin
Exception in thread Parse Parameters Thread:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "sentry_sdk\integrations\threading.py", line 69, in run
  File "sentry_sdk\_compat.py", line 55, in reraise
  File "sentry_sdk\integrations\threading.py", line 67, in run
  File "threading.py", line 870, in run
  File "C:\Users\ssivagur\CellProfiler-plugins\active_plugins\runimagejscript.py", line 377, in get_parameters_from_script
    self.init_pyimagej()
  File "C:\Users\ssivagur\CellProfiler-plugins\active_plugins\runimagejscript.py", line 350, in init_pyimagej
    if ijbridge.init_pyimagej(init_string):
  File "C:\Users\ssivagur\CellProfiler-plugins\active_plugins\cpij\bridge.py", line 86, in init_pyimagej
    result = from_imagej().get()
  File "<string>", line 2, in get
  File "multiprocessing\managers.py", line 835, in _callmethod
  File "multiprocessing\connection.py", line 250, in recv
  File "multiprocessing\connection.py", line 414, in _recv_bytes
  File "multiprocessing\connection.py", line 379, in _recv
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```
@hinerm

**Comment by bethac07** [comment]
@sugan89 This is in conda on Windows 10, yes?

**Comment by hinerm** [comment]
Hi @sugan89 - so sorry you're running into this problem!

It was a [known issue](https://forum.image.sc/t/cant-start-pyimagej-maven-path-not-found/82076/8) with the Maven conda-forge feedstock, just affecting windows.

This issue [was already resolved](https://github.com/conda-forge/maven-feedstock/issues/23) so it's a little concerning that it isn't working for a fresh install. What does `conda list` report in your environment? I just tested with `3.9.4-h57928b3_0` and it seems to work.

There's also an [entry in our Troubleshooting.md](https://github.com/imagej/pyimagej/blob/main/doc/Troubleshooting.md#jgojgoexecutablenotfound-mvn-not-found-on-path-) that might be helpful... you just use the command: `conda update -n [name_of_your_environment] maven`. If you can't get the conda-installed Maven working you can always [manually install it](https://maven.apache.org/install.html).

OK, try these things and let me know how it goes!

**Comment by bethac07** [comment]
Yup, for some reason even though she installed today, conda gave her 3.9.1 - running `conda install maven=3.9.4` inside the environment fixed the issue. She's now getting the same `_pickle.PicklingError: Can't pickle <java class 'java.lang.String'>: attribute lookup java.lang.String on jpype._jstring failed` I'm seeing in #218, trying now to see if downgrade also helps there, but will report that there. Thanks for the quick solve!
