### ISSUE TITLE
Issues running RunImageJScript plugin - pyimageJ version?

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler-plugins#218]
Hey @hinerm, having some issues getting RunImageJScript running on my Mac (M1, OS 13.4.1, installed in conda). I tried a few commits (as far back as https://github.com/CellProfiler/CellProfiler-plugins/commit/0c75579b0e6c44057a0f40e0eec80edfe42b5ddf), and those all gave the same behavior; rolling back to pyimageJ 1.1.1 seems to fix the issue, so seems to be something there (did not try anything other than most recent 1.4.1 and that version). Can you see if anything jumps out to you? Thanks!

```
[INFO] Overriding Leica ROI Reader; identifier: command:de.biovoxxel.utilities.RoiReader; jar: file:/Applications/Fiji.app/plugins/Biovoxxel_Plugins-2.6.0.jar
[INFO] Overriding Create framed inset Zoom; identifier: command:inset.creator.Inset_Creator; jar: file:/Applications/Fiji.app/plugins/BioVoxxel_Figure_Tools-1.13.1.jar
[INFO] Overriding Export SVG; identifier: command:svg.gui.SVGExporter; jar: file:/Applications/Fiji.app/plugins/BioVoxxel_Figure_Tools-1.13.1.jar
[INFO] Overriding Export all images as SVG; identifier: command:svg.gui.BatchSvgExporter; jar: file:/Applications/Fiji.app/plugins/BioVoxxel_Figure_Tools-1.13.1.jar
[INFO] Overriding Export time series as SVGs; identifier: command:svg.gui.TimeSeriesSvgExporter; jar: file:/Applications/Fiji.app/plugins/BioVoxxel_Figure_Tools-1.13.1.jar
[INFO] Overriding Import images from SVG; identifier: command:svg.gui.SVGImageImporter; jar: file:/Applications/Fiji.app/plugins/BioVoxxel_Figure_Tools-1.13.1.jar
[INFO] Overriding LUT Channels Tool; identifier: command:lut.tool.LutChannelsTool; jar: file:/Applications/Fiji.app/plugins/BioVoxxel_Figure_Tools-1.13.1.jar
[INFO] Overriding Meta-D-Rex; identifier: command:metadataRecorder.MetadataRecorder; jar: file:/Applications/Fiji.app/plugins/BioVoxxel_Figure_Tools-1.13.1.jar
[INFO] Overriding Start IJ Scale Bar; identifier: command:svg.gui.StartJIScaleBar; jar: file:/Applications/Fiji.app/plugins/BioVoxxel_Figure_Tools-1.13.1.jar
The synchronize_ij1_to_ij2 function is deprecated. Use sync_image instead.
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/cellprofiler_imagejscript/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/cellprofiler_imagejscript/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler-plugins/active_plugins/cpij/server.py", line 496, in main
    _start_imagej_process()
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler-plugins/active_plugins/cpij/server.py", line 390, in _start_imagej_process
    output_queue.put({PYIMAGEJ_KEY_OUTPUT: output_dict})
  File "<string>", line 2, in put
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/cellprofiler_imagejscript/lib/python3.8/multiprocessing/managers.py", line 834, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/cellprofiler_imagejscript/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/cellprofiler_imagejscript/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <java class 'java.lang.String'>: attribute lookup java.lang.String on jpype._jstring failed
Failed to run module RunImageJScript
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/cellprofiler_imagejscript/lib/python3.8/site-packages/cellprofiler/gui/pipelinecontroller.py", line 3390, in do_step
    self.__pipeline.run_module(module, workspace_model)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/cellprofiler_imagejscript/lib/python3.8/site-packages/cellprofiler_core/pipeline/_pipeline.py", line 1349, in run_module
    module.run(workspace)
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler-plugins/active_plugins/runimagejscript.py", line 657, in run
    ij_return = ijbridge.from_imagej().get()
  File "<string>", line 2, in get
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/cellprofiler_imagejscript/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/cellprofiler_imagejscript/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/cellprofiler_imagejscript/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/cellprofiler_imagejscript/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

**Comment by bethac07** [comment]
cc also @elevans , since it's a PyimageJ thing

**Comment by bethac07** [comment]
In case it's helpful for you for troubleshooting, I was just [using the pipeline and script from the pyimagej paper](https://drive.google.com/file/d/1mZSbMNLDqVuR690yseR37umiDQN-7S43/view?usp=sharing)

**Comment by hinerm** [comment]
@bethac07 currently [stuck on installing CP](https://github.com/CellProfiler/centrosome/issues/121) 😿

**Comment by elevans** [comment]
Are you testing on windows?

**Comment by hinerm** [comment]
@bethac07 so my cp installation completed but when I tried to run it I get this error:
```
(cp-ij) C:\Users\hiner\code\cellprofiler\CellProfiler-plugins>cellprofiler
usage: cellprofiler [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: cellprofiler --help [cmd1 cmd2 ...]
   or: cellprofiler --help-commands
   or: cellprofiler cmd --help
```

I tried `--help-commands` but get:
```
(cp-ij) C:\Users\hiner\code\cellprofiler\CellProfiler-plugins>cellprofiler --help-commands
Usage: cellprofiler [options] [<output-file>])
         where <output-file> is the optional filename for the output file of
               measurements when running headless.
         The flags -p, -r and -c are required for a headless run.

cellprofiler: error: no such option: --help-commands
```

Do you want issues for these?

[Starting CellProfiler](https://github.com/CellProfiler/CellProfiler/wiki/Source-installation-%28Windows%29#starting-cellprofiler) says no-args should just start the GUI, like it used to... did that change?

**Comment by bethac07** [comment]
Can you move the setup.py file? This seems likely to be this: https://github.com/CellProfiler/CellProfiler-plugins/pull/216

**Comment by hinerm** [comment]
>Disclaimer - this is gross, and I feel gross about it, but it might be the least-worst thing

😻

**Comment by bethac07** [comment]
Now accepting suggestions for less gross things, if you have them! :)

**Comment by hinerm** [comment]
Well the fix worked at least.. so, one thing at a time. Thanks @bethac07 ❤️

**Comment by hinerm** [comment]
@elevans I think the culprit could be a jpype/Java string attached to the `xarray.core.dataarray.DataArray` that results from converting `ij.ImagePlus` using `ij.py.from_java`.

I'm basing this off, if I change [this line](https://github.com/CellProfiler/CellProfiler-plugins/blob/7682fb00072de69604387fca5e0a947db033f3ad/active_plugins/cpij/server.py#L388C29-L388C29) to `output_dict[key] = {}` the script runs without error (although the output is of course useless).

So we need to find where the jpype string is infecting our python data structure.

**Comment by hinerm** [comment]
> So we need to find where the jpype string is infecting our python data structure.

found it:
![image](https://github.com/CellProfiler/CellProfiler-plugins/assets/1123809/2d18d646-7a2c-4b06-b2e7-6e42aa99748d)

So the `DataArray` names are Java strings instead of python strings. Naughty.

**Comment by hinerm** [comment]
@bethac07 fixed in [PyImageJ](https://github.com/imagej/pyimagej/commit/a1861b6c1658d6751fa314650b13411f956549ab) and intermediary patch [PR submitted](https://github.com/CellProfiler/CellProfiler-plugins/pull/219). LMK if you need anything else.
