### ISSUE TITLE
MeasureRadialEntropy returns indexing error

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler-plugins#25]
Using MeasureRadialEntropy returns the following error:

```
Failed to run module MeasureRadialEntropy
Traceback (most recent call last):
  File "cellprofiler\gui\pipelinecontroller.py", line 2887, in do_step
    self.__pipeline.run_module(module, workspace)
  File "cellprofiler\pipeline.py", line 2011, in run_module
    module.run(workspace)
  File "C:\Users\karhohs\Documents\GitHub\CellProfiler-plugins\measureradialentropy.py", line 90, in run
    measurements.add_measurement(input_object_name,feature_bin,slicemeasurements[:,eachbin])
IndexError: too many indices for array
```

**Comment by AnneCarpenter** [comment]
Dude, post images + pipeline please 😉
